### ISSUE TITLE
Error: Unexpected token 

### ISSUE THREAD

**Issue by veeramarni** [apollostack/graphql-document-collector#5]
I'm getting following error, when i was trying with `meteor-starter-kit`

```
$ graphql-document-collector '**/*.graphql' > documents.json
/Users/dre/.nvm/versions/node/v5.0.0/lib/node_modules/graphql-document-collector/bin/graphql-document-collector:3
const {default: loadTransformAndFlatten} = require('../lib');
      ^

SyntaxError: Unexpected token {
    at exports.runInThisContext (vm.js:53:16)
    at Module._compile (module.js:404:25)
    at Object.Module._extensions..js (module.js:432:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:311:12)
    at Function.Module.runMain (module.js:457:10)
    at startup (node.js:136:18)
    at node.js:972:3

```

**Comment by rricard** [comment]
Sorry, just saw it, can you try with a newer node version please? You can use nvm to switch versions easily: https://github.com/creationix/nvm
